### ISSUE TITLE
Hyperparameter Training 

### ISSUE THREAD

**Issue by anabia-alam** [aws-samples/amazon-sagemaker-pytorch-detectron2#12]
Hello,

I am running hyperparameter optimization on my custom dataset. But the job is failing with Cuda memory error, 
- Skip loading parameter 'head.cls_score.bias' to the model due to incompatible shapes: (720,) in the checkpoint but (1278,) in the model! You might want to double check if this is expected.
- Traceback (most recent call last):
  File "training.py", line 472, in <module>
    train(_parse_args())
  File "training.py", line 219, in train
    args=(args,),
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/detectron2/modeling/backbone/fpn.py", line 142, in forward
  File "/opt/conda/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "training.py", line 156, in _train_impl
    trainer.train()
  File "/opt/conda/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 431, in train
    super().train(self.start_iter, self.max_iter)
  File "/opt/conda/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
    prev_features = lateral_features + top_down_features
- RuntimeError: CUDA out of memory. Tried to allocate 252.00 MiB (GPU 0; 15.78 GiB total capacity; 14.03 GiB already allocated; 190.75 MiB free; 14.46 GiB reserved in total by PyTorch)

Can you elaborate on how this issue should be tackled?
TIA

**Comment by paoloirrera** [comment]
Hello,
The first point (incompatible shapes) is perfectly normal. As for the out of memory, try to reduce batch-size.

**Comment by anabia-alam** [comment]
Thanks for responding. Could it be because of an exhaustive search against continuous variables, which tends to take memory? like this
hparams_range = {
    "lr": ContinuousParameter(0.0005, 0.1),
}

**Comment by paoloirrera** [comment]
No, it is not because of that. A SM tuning job launches a set of SM training job in parallel. What is failing is one or more of you SM training jobs. Exhaustive search has not anything to do with your issue, plus SM does not use exhaustive search for HP optimization.
I suggest to read the sagemaker [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning.html) on tuning jobs and look at an [example](https://sagemaker-examples.readthedocs.io/en/latest/hyperparameter_tuning/pytorch_mnist/hpo_pytorch_mnist.html).
